name: "WordPress.org SVN deployment"

on:
  release:
    types: [released]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion
      - name: Deploy
        run: chmod +x ./deploy.sh && ./deploy.sh
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}